files:
- generatedChecksum: C2B88D9215301ECE3DC36E4B82F2791C
  logicalPath: config/pic32mk_gp_db
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C2B88D9215301ECE3DC36E4B82F2791C
- generatedChecksum: F3886D06BCA3A5AC00D7187868F85B02
  logicalPath: config/pic32mk_gp_db
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: F3886D06BCA3A5AC00D7187868F85B02
- generatedChecksum: E1C08FE85F45990D5B49FF7F916F685B
  logicalPath: config/pic32mk_gp_db
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: E1C08FE85F45990D5B49FF7F916F685B
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: D825045394F8C6872CB99AA8AA491DE5
  logicalPath: config/pic32mk_gp_db/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: D825045394F8C6872CB99AA8AA491DE5
- generatedChecksum: CC0CAE10ABECEB9834034B0002657A75
  logicalPath: config/pic32mk_gp_db/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: CC0CAE10ABECEB9834034B0002657A75
- generatedChecksum: 852DBAF5BAFB0086787DD590B4FDD1E0
  logicalPath: config/pic32mk_gp_db/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 852DBAF5BAFB0086787DD590B4FDD1E0
- generatedChecksum: F2085ED4B309D384EB77BBD22A663979
  logicalPath: config/pic32mk_gp_db/peripheral/uart
  name: plib_uart3.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: F2085ED4B309D384EB77BBD22A663979
- generatedChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
  logicalPath: config/pic32mk_gp_db/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
- generatedChecksum: 8E3D30ADF309D1DBD1DD4C2A31420650
  logicalPath: config/pic32mk_gp_db
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 8E3D30ADF309D1DBD1DD4C2A31420650
- generatedChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
  logicalPath: config/pic32mk_gp_db
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_gp_db/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: A1364CE634E5EDFC0CD338822137A62D
  logicalPath: config/pic32mk_gp_db/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: A1364CE634E5EDFC0CD338822137A62D
- generatedChecksum: 94CE06E936A42869D2C332ECC3CAB7F4
  logicalPath: config/pic32mk_gp_db/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 94CE06E936A42869D2C332ECC3CAB7F4
- generatedChecksum: B9C4D720AAFC79723C58264CCAC74E9A
  logicalPath: config/pic32mk_gp_db/peripheral/uart
  name: plib_uart3.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: B9C4D720AAFC79723C58264CCAC74E9A
- generatedChecksum: CB4B34D1ABCE74BF62A89A7FF936BE91
  logicalPath: config/pic32mk_gp_db/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: CB4B34D1ABCE74BF62A89A7FF936BE91
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mk_gp_db
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: DE57CE7992ED2DD2523C62496F6637E7
  logicalPath: config/pic32mk_gp_db
  name: p32MK1024GPE100.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: DE57CE7992ED2DD2523C62496F6637E7
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_gp_db;../src/packs/PIC32MK1024GPE100_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_gp_db;../src/packs/PIC32MK1024GPE100_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
